### ISSUE TITLE
X-Request-Id instead of X-Vcap-Request-Id

### ISSUE THREAD

**Issue by oppegard** [cloudfoundry/gorouter#148]
By default, a Ruby on Rails app will tag all logs with the value of X-Request-Id. For example, here's a request to a Rails 5 app on Pivotal Web Services:

```sh
$ curl -I https://rails5.cfapps.io/
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Fri, 26 Aug 2016 23:30:36 GMT
X-Request-Id: 55bdeb17-ad2d-4c59-b033-bee8a8e6430d
X-Runtime: 0.002347
X-Vcap-Request-Id: 4bf49bd8-7e62-4a09-720c-2cd4443e8d87
Connection: keep-alive
```

And the corresponding `cf logs` output:
```
2016-08-26T17:30:36.49-0600 [APP/0]      OUT I, [2016-08-26T23:30:36.498456 #20]  INFO -- : [55bdeb17-ad2d-4c59-b033-bee8a8e6430d] method=HEAD path=/ format=*/* controller=WelcomeController action=index status=200 duration=1.13 view=0.81 db=0.00 params={}
2016-08-26T17:30:36.50-0600 [RTR/3]      OUT rails5.cfapps.io - [26/08/2016:23:30:36.497 +0000] "HEAD / HTTP/1.1" 200 0 0 "-" "curl/7.43.0" 10.10.2.230:38653 x_forwarded_for:"50.232.79.2" x_forwarded_proto:"https" vcap_request_id:4bf49bd8-7e62-4a09-720c-2cd4443e8d87 response_time:0.007176212 app_id:3e7d31a6-e880-4f50-ae05-149fc44c4257
```

The app log includes X-Request-Id of `55bdeb17-ad2d-4c59-b033-bee8a8e6430d`. Has there been consideration of adopting X-Request-Id in place of X-Vcap-Request-Id? It would improve the developer experience of correlating gorouter logs with application logs.

**Comment by shalako** [comment]
Hi Glenn,

Unfortunately, there are no standards in the tracing community. I'm feeling particularly frustrated about this at the moment. 

Years ago, the Cloud Foundry dev team had Gorouter initiate `X-Vcap-Request-Id`, and many of the CF components passed this header through and it has been very helpful in troubleshooting internal Cloud Foundry system interactions. I'm not sure we can remove support for that; I believe there's logic for it throughout the CF system components. 

Recently we added support for Zipkin tracing, because surprise(!) Zipkin doesn't work with anything but it's own headers. So when enabled, Gorouter will send backends `X-B3-TraceId`, `X-B3-SpanId`, and `X-B3-ParentSpanId`. 

I'm not surprised to hear Rails has its own tracing header. Where does it end? We would have to add another optional deployment switch for "Rails tracing" to send `X-Request-Id`, because with every additional header the app request payloads grow and the router access logs grow.

`1000 requests / second * 30 Bytes = 2.4 GB / day`, just to log the additional header.

Maybe you could use a Zipkin library with your app to handle logging of tracing data? Then you could correlate the Zipkin trace id logged by the app with the same id logged by the router.

Thoughts?

**Comment by oppegard** [comment]
Hi Shannon,

Thanks for taking the time to give a thoughtful response. Rails most likely adopted `X-Request-Id` from Heroku: https://devcenter.heroku.com/articles/http-request-id

Perhaps we should instead try a PR for Rails that allows the header to be configurable, while defaulting to Heroku's `X-Request-Id`.

**Comment by shalako** [comment]
Thank you, Glenn. I don't want you to feel like we're leaving Rails in the cold, bu I would love to avoid adding many more trace ids if there's a painless workaround.

If Rails can't use a configurable header natively, there are Zipkin libraries for most frameworks. FWIW, Zipkin came out of Twitter and seems to be a popular tracing spec. Here's a ruby lib I found, I suspect there are others: https://github.com/openzipkin/zipkin-ruby

I'll close this issue for now; please feel free to re-open with followup questions.
