### ISSUE TITLE
gorouter lost some nats messages in a large deployment

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/gorouter#166]
## Issue

If the Diego contains 200,000 app instances, the route_emitter sends the 200,000 route nats message ("router.register") at the same time, that overloads the nats client in gorouter, and some nats messages are just dropped by nats client in gorouter.

## Possible Fix

The possible cause is this issue opened in nats: https://github.com/nats-io/gnatsd/issues/217, and the solution is using SetPendingLimits to set a bigger cache, but gorouter is using the default pending limits (65536).

**Comment by shalako** [comment]
Prioritizing for engineering review.

**Comment by flawedmatrix** [comment]
Hello @JimmyMa 
After some initial testing, we were able to to successfully have 200K routes registered in Gorouter when using local Route Emitters (each cell has its own route emitter which emits to NATS only the routes for apps on that cell). This should solve the issue of having too many NATS messages emitted at the same time.

This experimental feature is supported since Diego Release v1.6.2, but I recommend using the latest Diego Release version to pull in bug fixes for local Route Emitters.

Does this solve the issue for you?

**Comment by shalako** [comment]
Hello @JimmyMa we've also tested that by using the new colocated emitter architecture @flawedmatrix described, we can register a total of 400k routes from four emitters (each 100k), and the router doesn't miss a route.

We recommend using this feature in the latest version of Diego as a solution to your use case.

We'll close this issue; please reach out if you have any follow up questions. 
Thank you!
