### ISSUE TITLE
Route Services are NOT invoked when a bound route is NOT mapped to an application.

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/gorouter#206]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue
A route service handler is not invoked if the route is not mapped to a Cloud Foundry application. 

## Context
While I understand that this was a conscious decision taken earlier, I would like to question this. In essence, a route service works on routes and while routes are connected to applications, a app-route mapping may not always be necessary. 
For example, there could be third party services that require access over a Cloud Foundry route. In such cases, deploying a Cloud Foundry application is unnecessary and may not be possible as well. 
The route service can forward the request to the third-party endpoint without any interaction with the Cloud Foundry subsystem at all. 
With the current state, the route has to be mapped to an application for the proxying to work.

## Steps to Reproduce
- Deploy the service broker application
  - The bind workflow must return back the URL for the route service application
- Create the service broker using `cf create-service-broker` and enable service access
- Create a service instance using `cf create-service`
- Create a route using `cf create-route`
- Bind the route to the service instance using `cf bind-route-service`
- Invoke the route
- Tail the route service app logs to see if the route service was invoked

## Expected result
- The route service must be invoked

## Current result
- The route service is not invoked

## Possible Fix
- Remove possible check in the GoRouter that checks for an application mapping for the route

**Comment by shalako** [comment]
Hello @abh1kg 
As you've discovered, Cloud Foundry doesn't support routing of requests to addresses that are not associated with applications. 

We do plan to enable this use case, but not in Gorouter. The CF Routing team is currently focussed on integrating Envoy and Istio with Cloud Foundry, and we intend to enable Envoy to know about routes that are not mapped to apps. There is still quite a lot of work to do before we can recommend using Istio and Envoy instead of the existing routing subsystem, including re-implementing support for Route Services.

**Comment by shubhaat** [comment]
Closing this issue since we don't plan to support it in Gorouter but definitely want to support it in the new Istio based routing subsystem. The proposal is here: https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit
