### ISSUE TITLE
Tens of thousands of sockets in CLOSE_WAIT status

### ISSUE THREAD

**Issue by libnux** [cloudfoundry/gorouter#238]
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Tens of thousands of sockets in CLOSE_WAIT status, and they occupied large amount of memeory and used up FD. The overall performance was greatly degraded.

## Context

Gorouter release in cf.v237

## Steps to Reproduce

Start gorouter and after several minutes, the sum of CLOSE_WAIT sockets accumulated to more than 50000:

netstat -n | awk '/^tcp/ {++S[$NF]} END {for (s in S) print s,S[s]}'
FIN_WAIT2 2
SYN_RECV 1
**CLOSE_WAIT 79564**
TIME_WAIT 1427
ESTABLISHED 3451
LAST_ACK 11396
SYN_SENT 506
FIN_WAIT1 2

## Expected result

Much fewer socket in CLOSE_WAIT state

## Current result

more then 50000 in CLOSE_WAIT state

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` Output Results

[if relevant, include a screenshot]

**Comment by shubhaat** [comment]
It looks like you are on cf-release and we have since deprecated [cf-release](https://github.com/cloudfoundry-attic/cf-release) and no longer support it. We recommend you migrate to cf-deployment, to read more about migration [here](https://github.com/cloudfoundry/cf-deployment-transition)

CF Routing Team

**Comment by shalako** [comment]
Closing this for now; please reopen if you observe using a more recent version of cf-deployment.
