### ISSUE TITLE
Gorouter should emit 404 on missing instance and 400 for bad instance id header

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/gorouter#264]
## Issue

This seems to be a regression.

As described in https://github.com/cloudfoundry/gorouter/commit/a3583dbc8553d4a0902a42d7fa9ccddf03e54c56 gorouter should return 400 on malformed `X-CF-APP-INSTANCE` header and 404 if the instance denoted by said header does not exist.

This is also the described behavior in https://github.com/cloudfoundry/gorouter#headers (although the 400 response is missing)

Since we rolled out release 0.198.0 to production, our clients are complaining this behavior has changed. In both cases there is 400 bad request returned. This undocumented change has thrown off some customers as they had based their B/G deployment cycles on the status codes.

## Context

This happens whenever you use the `X-CF-APP-INSTANCE` to address a specific instance of your app.

## Steps to Reproduce

1. Deploy an app with only one instance
2. Do

```
curl -H "X-CF-APP-INSTANCE: <app-id>:1" https://my-app.com/
```

## Expected result

```
404 Not Found: Requested instance ('1') with guid (<app-id>) does not exist for route ('my-app.com')
```

## Current result

```
400 Bad Request: Requested instance ('1') with guid (<app-id>) does not exist for route ('my-app.com')
```

## Possible Fix

- Restore old behavior (400 on bad header, 404 on missing instance)
- Update documentation

[Slack thread](https://cloudfoundry.slack.com/archives/CFX13JK7B/p1581323910042700)

**Comment by domdom82** [comment]
Relevant section in docs: https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html

"Routing Requests to a Specific App Instance" heading

**Comment by tlwr** [comment]
_Drive-by and perhaps vexatious comment, sorry_

---

Relevant comment from Slack from @bruce-ricard:

> The rationale was that a non existing instance in the header is in fact a malformed header. Our understanding is that 404s should only be used when the URL itself doesn't match any page, not when some post parameter or header is "not found". One argument for this is that some load balancers cache 404s from their backends. Please let us know if you have a different understanding.

I think the 400 is counter-intuitive and potential hostile to users, however the comment about load balancers caching 404s is useful to keep in mind.

There is probably additional context from the [associated pivotal story](https://www.pivotaltracker.com/story/show/170191495) with the commit (02af2cad0eef9966a118bdb4d24819f658e48c36) which changed this behaviour. However this story is private.

---

When gorouter handles missing routes, which is called either when:

- the pool is empty (so nothing can handle the request) and gorouter is configured to not serve a 503
- there is no pool for this route (so there are no registered backends)
- the lookup has reported there is no instance with this instance ID

during this request path, it adds the header `Cache-Control: no-cache,no-store`, which means the client (or an intermediate load balancer) should _never_ cache this response

---

With the above:

- any load balancer which caches a 404 from gorouter, when any of the above 404 cases has been hit, is [violating RFC 7234](https://tools.ietf.org/html/rfc7234#section-5.2.2.3) (this RFC is only 5.5 years old though)
- as a user, when I make a valid and well-formed request, to a resource which does not exist, getting a 400 instead of a 404 is counter-intuitive

[This commit from my dev remote (404)](https://github.com/tlwr/gorouter/commit/ca8069780b3c1c7022a4bcb43cbf7cdbb88239f3) can be cherry-picked to make this change (404), the change is very simple, and the tests already assert the headers are correct.

---

Alternatively, there is actually a HTTP status code specifically for this use case, as defined in [RFC 7232](https://tools.ietf.org/html/rfc7232#section-4.2): HTTP 412 Precondition Failed.

> The 412 (Precondition Failed) status code indicates that one or more
   conditions given in the request header fields evaluated to false when
   tested on the server. 

[This commit from my dev remote (412)](https://github.com/tlwr/gorouter/commit/85290277d8545ca8c0eff43ec71d103796a5f86e) can be cherry-picked to make this change (412). As above, the change is simple, and the tests already assert the correct behavior.

IMO a 412 is better than a 404, which is better than a 400.

**Comment by domdom82** [comment]
Whatever we choose to respond with, it should be clearly communicated because a change in status codes is basically a change to the user API without deprecation notice. Such changes should always be part of release notes and doc updates.

If we picked @tlwr s commit at least the docs would match the behavior again :)
This would unblock my clients for now until a proper doc update + logic change is released.

**Comment by ameowlia** [comment]
Hi @domdom82, 

First I'd like to apologize for the pain that this undocumented change caused you.

We have decided to stick with returning the 400. I updated the [release note](https://github.com/cloudfoundry/routing-release/releases/tag/0.197.0) to include this reasoning: 
```
Breaking change: Requests with nonexistent instance ID headers and with syntactically incorrect instance ID headers will now return a 400 status code instead of a 404 status code. A 400 status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). We think this is better than a 404 which indicates page not found.
```

I also updated the following docs: 
- [gorouter docs](https://github.com/cloudfoundry/gorouter/commit/d44c87d6ee66d4fdd9d053e4c6365924cb4a6d74)
- [CF Docs](https://github.com/cloudfoundry/docs-dev-guide/pull/390)

We will try to do better at communicating these changes in the future. I'm not sure how this one slipped by. 

I'm closing the issue. Feel free to reopen if you have any other questions or reach out to us in slack.

Best, 
Amelia Downs, CF Networking Program Engineer

**Comment by KauzClay** [comment]
Hi @domdom82,

Thanks for bringing this up. I apologize for the lack of documentation on this change. We are working on updating the documentation to reflect the current behavior.

For visibility, here is a link to a slack conversation on this topic: https://cloudfoundry.slack.com/archives/CFX13JK7B/p1581323910042700

For now, we will retain what we have, but I believe the discussion is still ongoing as to what the appropriate error code is.

**Comment by domdom82** [comment]
@ameowlia thanks for the quick fix. My clients will update their apps to the new behavior.
