### ISSUE TITLE
ADD CUSTOM HEADERS to GOROUTER PATHS

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/gorouter#279]
Please report all issues and feature requests in [cloudfoundry/routing-release](https://github.com/cloudfoundry/routing-release) instead of here. Thanks!
Dear Sir,

Can we add custom headers to paths like we can do in nginx to GO ROUTER

**Comment by ameowlia** [comment]
Hi @viju2008, 

It sounds like you want to add custom headers to requests for certain routes.

**1. I suggest using route services**
There is currently a way to do this using route services: 
1. Make a route service that adds this header
2. Bind this route service to the appropriate routes 

Here are some docs on route services to get you started: https://docs.cloudfoundry.org/services/route-services.html

**2. Doing this natively would be a lot of work**
The alternative to route services would be to add this natively. This would include: 
1. changing the CLI to take a new "additional headers" property
2. changing CAPI to store these properties in the DB and to send them to BBS
3. changing the BBS to store these properties
4. changing route-emitter to send these properties per route
5. changing gorouter to respect this new property 

Given that this would require changes to 3 releases and the CLI _and_ because there is already an alternative (route services) we would not prioritize this without a lot more community members asking for it. 

**3. Adding support for adding the same header on all requests would be easier**
However, if all you need is to add a custom header on _all_ requests, that would be an easy PR for you to add. We already have a [property to do something similar on responses](https://github.com/cloudfoundry/routing-release/blob/3fb70d55327eb16f3dc42268e7c869957c520972/jobs/gorouter/spec#L218-L225). 

If you decide to re-open this issue, please follow the rules listed and "_Please report all issues and feature requests in [cloudfoundry/routing-release](https://github.com/cloudfoundry/routing-release) instead of here_".

Thanks, 
Amelia Downs, CF Networking Team Member
